### PR TITLE
Polish makefile

### PR DESCRIPTION
**Pull request by FranklinYu**
Continues #2. Some are personal tastes, so discussion welcome.

### CODE REVIEW

**Comment by franklinyu** [comment]
Bump.

**Comment by franklinyu** [comment]
Bump.

**Comment by jfkami** [comment]
how do i make the unback?

**Comment by FranklinYu** [comment]
@jfkami I guess that’s a question about the project, not about this Pull Request?

**Review by LaikaN57 — APPROVED** [review]

**Comment by pabs3** [comment]
@inflex I'd like to see this merged too, I've got a WIP cleanup branch that will affect the Makefile too, so I'd prefer to build on top of this branch to avoid conflicts.

**Comment by pabs3** [comment]
Thanks!

**Pull request merged**
